#端口号
server:
  port: 8082

logging:
  level:
    learning: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pactera?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    connectionProperties: druid.stat.mergeSql=true
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    check-template: true
#  security:
#    user:
#      name: zhangxiaopan
#      password: 123456
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: src/main/resources/static/**,src/main/resources/template/**



mybatis:
  type-aliases-package: com.pactera.**.model
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

myprops:
  key: abcdefgabcdefg12
