#端口号
server:
  port: 8088

logging:
  level:
    learning: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pectera?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: zhangxp
    driver-class-name: com.mysql.jdbc.Driver
    connectionProperties: druid.stat.mergeSql=true
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    check-template: true



mybatis:
  type-aliases-package: com.pectera.spring.model
  mapper-locations: classpath:mappers/*.xml
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql